### ISSUE TITLE
IE 9 & 10 Support

### ISSUE THREAD

**Issue by spencer516** [RavelLaw/e3#14]
Needs investigation; current word is that it ain't working.

**Comment by elwayman02** [comment]
:+1: I was just about to open this lol

**Comment by spencer516** [comment]
:smiley:

**Comment by spencer516** [comment]
@elwayman02 — I just verified on IE10. https://github.com/RavelLaw/e3/pull/20 ...looks like IE and Firefox don't like tags inside buttons (or something). I think we're okay here.
