### ISSUE TITLE
Demo does not seem to work on Firefox 40 and DE

### ISSUE THREAD

**Issue by Serabe** [RavelLaw/e3#19]
Demo page does not seem to work in Firefox 40 and Firefox Developer Edition. Does not transition to any other route, but shows no error in the console.

**Comment by spencer516** [comment]
Suspect this is related to: https://github.com/RavelLaw/e3/issues/14 

I'm going to try to investigate this today.

**Comment by spencer516** [comment]
@Serabe — it should be fixed now. Take a look and let us know if you notice any other issues!

**Comment by Serabe** [comment]
Thank you!
